FROM python:3.14-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_ENV=production

EXPOSE 3000

CMD ["gunicorn", "-b", "0.0.0.0:3000", "main:app"]